wallpaper {
  monitor = HDMI-A-1
  # path = ~/wallpapers/tigers-roaring-3840x2160-12730.jpg
  path = ~/repos/wallpapers/ign_mandalorian.jpg
  fit_mode = cover
}

wallpaper {
  monitor = DP-2
  path = ~/wallpapers/black-panther-ai-3840x2160-17094.jpg
  fit_mode = cover
}
